### PR TITLE
Make PUT /v1/referrals/{transactionID} idempotent

### LINKED ISSUE #574: referral finalization endpoint is not idempotent
If promo sends finalized referrals that eyeshade already has, eyeshade returns a 422.  This locks up the referral server which will continually try to send the same download ids and revert once it fails.

Instead of returning a 422 when eyeshade sends downloads that have already been confirmed, let's accept them and return 200.

### PR DESCRIPTION
**Pull request by nvonpentz**
Also add tests for referrals
Resolves #574
Let me know if I left too many comments.

### CODE REVIEW

File: eyeshade/controllers/referrals.js [hunk 1]
```diff
@@ -74,29 +74,39 @@ v1.createReferrals = {
       const payload = request.payload
       const debug = braveHapi.debug(module, request)
       const referrals = runtime.database.get('referrals', debug)
-      let entries, matches, probi, query
+      const downloadIdsToBeConfirmed = []
+      let entries, existingDownloadIds, probi
 
       entries = await referrals.find({ transactionId: transactionId })
-      if (entries.length > 0) return reply(boom.badData('existing transaction-identifier: ' + transactionId))
+      if (entries.length > 0) return reply({})
```
Comment (evq) [inline eyeshade/controllers/referrals.js]: I wonder if we should avoid early return here. as it's possible (although unlikely) that some referrals were added to the collection and others were not

Comment (nvonpentz) [reply eyeshade/controllers/referrals.js]: Yes, you're right.  I don't think we care if there already is a referral with the same transaction id.  We should only care about download id.  I will remove this line.

In practice though I don't think this should be too much of a problem since txId is effectively a request id, since a new one is used every request.  So in the case you described, the referrals should just go through on the next request.

Comment (nvonpentz) [reply eyeshade/controllers/referrals.js]: Added a fix + test in 07c466d
