### PR TITLE
fixes stats types passed through url params

### LINKED ISSUE #691: add amount received by BAT cards to settlement stats endpoint
basically we'll want to look at settlement txns where `settlement_currency` = `BAT`

### PR DESCRIPTION
**Pull request by maikelmclauflin**
fixes #691

### CODE REVIEW

**Comment by evq** [comment]
```
  1 test failed
  eyeshade › transaction.integration › transaction stats
  /home/travis/build/[secure]-intl/bat-ledger/node_modules/ava/lib/assert.js:56
  contributions are summed
  Difference:
  - 19
  + 0
  new AssertionError (node_modules/ava/lib/assert.js:56:10)
  Test.is (node_modules/ava/lib/assert.js:264:17)
  is (test/eyeshade/transaction.integration.test.js:446:7)
  process._tickDomainCallback (internal/process/next_tick.js:229:7)
``

File: eyeshade/controllers/stats.js [hunk 1]
```diff
@@ -83,6 +85,9 @@ v1.settlementsStats = {
   description: 'Retrieves information about bat paid out in referrals',
   tags: [ 'api' ],
   validate: {
+    query: Joi.object().keys({
+      currency: braveJoi.string().anycurrencyCode().optional().default('BAT').description('the settlement currency to query for')
```
Comment (evq) [inline eyeshade/controllers/stats.js]: maybe make this `settlement_currency`
